### PR TITLE
feat(Collection): add collection format methods

### PR DESCRIPTION
**Pull request by TheLionCub**

### CODE REVIEW

**Comment by Mirdukkk** [comment]
What the use case of this? I never see something like this

**Comment by TheLionCub** [comment]
It may be useful for sharing collection data between processes represented in a string, then we can easily create a collection on another process from it. And not only for sharing data, but also for storing it somewhere, e.g. in database. I haven't also seen this feature anywhere, so I think that it would be useful in mentioned cases.

**Comment by Mirdukkk** [comment]
In Discordoo, Collection is used to store circular structures that cannot be simply translated into a string using JSON.stringify. So I think we don't need this feature. After all, if someone needs to transfer the collection to another process, they can write these couple of lines themselves.

**Comment by TheLionCub** [comment]
But I haven't told that it's especially for Discordoo usages with its difficult structures storing in collection. As Collection is an additional package available for everyone, where a lot of simple methods have already been realized, I thought that these one won't be an exclusion.

**Comment by Mirdukkk** [comment]
The methods already implemented in the Collection are very suitable for use in many situations. But the toStringFormat and fromStringFormat methods can only be used in one situation - when you need to translate a collection to a string and back. For interprocess communication, the collection does not need to be translated into a string at all, it is enough to translate it into an array, because any libraries for interprocess communication in node.js (including the built-in one) are accepts not only strings, but also arrays, objects, and so on. I don't see any point in converting the collection to strings anywhere.

**Comment by TheLionCub** [comment]
Oh, ok, I agree with you in this way. This methods will allow to work properly with simple data in it, like [1, "2"], but there could appear troubles when working with objects (e.g. maps, classes, etc.), which are stored in a collection.

**Comment by Mirdukkk** [comment]
Thank you for your understanding and participation in the development! <3

**Pull request closed without merging**
